---
name: Community Meetings
description:  Schedule meetings for the CNPE Community.
title: "[Meetings] YYYY-MM-DD Community Meeting "
labels: [meeting]
projects: [cnpe-community/1]
body:
  - type: markdown
    attributes:
      value: |
        A Community Meeting is scheduled for:
  - type: input
    id: scheduled-date
    attributes:
      label: Scheduled Date
      description: "Please enter the day of the meeting (format: YYYY-MM-DD)"
      value: YYYY-MM-DD
    validations:
      required: false
  - type: input
    id: scheduled-time
    attributes:
      label: Scheduled Time
      description: "Please enter the time of the meeting and timezone (format: HH:MM AM/PM, e.g., 4:00 PM or 1600 BST)"
      value: 4:00 PM or 1600 BST
    validations:
      required: false
  - type: textarea
    attributes:
      label: Agenda Topics
      description: Topics for discussion
      value: |
        * Housekeeping and updates from Community leadership
          * TBD
        * Community Discussion
          * TBD
        * Guest Speaker
          * TBD
        * Initiative discussion
          * TBD
        * Open discussion / Platform Engineering Q&A
  - type: textarea
    attributes:
      label: Checklist
      description: Steps to prepare for the meeting
      value: |
        - [ ] Create meeting on LFX
        - [ ] Identify/select speaker(s)
        - [ ] Announce meeting (share Github issue) in community slack for agenda requests
        - [ ] Finalize Agenda
        - [ ] Announce meeting on social platforms
    validations:
      required: false